# Generated by Django 5.0.1 on 2024-01-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=100000)),
                ('min_points_to_earn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('points', models.IntegerField(default=0)),
                ('registration_date', models.DateTimeField()),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.avatar')),
            ],
        ),
    ]
